### ISSUE TITLE
'FLmode' is not defined while running 'IBM Plex export FDK files.py'

### ISSUE THREAD

**Issue by weiweihuanghuang** [IBM/plex#230]
Using Fontlab 5714 on macOS 10.13.6
```
---------------------------
* IBM Plex export for FDK *
---------------------------
Traceback (most recent call last):
  File "<string>", line 463, in <module>
NameError: name 'FLmode' is not defined
```

I think Fontlab *can* see robofab, because I can important in the Edit Macro window without a problem but it can't do this:

```
import os
from robofab.world import world
```

If I try that in the Edit Macro window I get this:
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Library/Python/2.7/site-packages/robofab/world.py", line 95, in <module>
    from robofab.objects.objectsFL import CurrentFont, CurrentGlyph, RFont, RGlyph, OpenFont, NewFont, AllFonts
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsFL.py", line 6, in <module>
    from robofab.objects.objectsBase import BaseFont, BaseGlyph, BaseContour, BaseSegment,\
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsBase.py", line 25, in <module>
    from robofab import ufoLib
  File "/Library/Python/2.7/site-packages/robofab/ufoLib.py", line 38, in <module>
    from robofab.glifLib import GlyphSet, READ_MODE, WRITE_MODE
  File "/Library/Python/2.7/site-packages/robofab/glifLib.py", line 19, in <module>
    from robofab.pens.pointPen import AbstractPointPen
  File "/Library/Python/2.7/site-packages/robofab/pens/pointPen.py", line 145, in <module>
    from fontTools.pens.basePen import AbstractPen
ImportError: No module named fontTools.pens.basePen

```
```

**Comment by weiweihuanghuang** [comment]
Seems like FL5 can't find fontTools? Which is certainly installed

**Comment by weiweihuanghuang** [comment]
Ok I think my issue was that fontTools was installed in python `/usr/local/lib/python2.7/site-packages` instead of /Library/Python/2.7/site-packages/
